import '../styles/globals.css'
import Head from 'next/head'

import Navigation from '../components/Navigation'

function MyApp({ Component, pageProps }) {
  return <main>
      <Head>
        <title>Rifqi Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <Navigation />

      <Component {...pageProps} /> 
    </main>
}

export default MyApp
